### ISSUE TITLE
Researching sensors for seat belt 

### ISSUE THREAD

**Issue by LTTien** [LTTien/MobilityEmbeddded#1]
## Description
Researching sensors for seat belt. 

## Definition of Done
- [ ] find the correct sensor

## Tasks
- [ ] try looking at how cars get the notification
- [ ] research how sensors work in general
- [ ] come up with 3 candidates for sensors options to choose from.

**Comment by LTTien** [comment]
> from:richard cross to:Lynne Tien
Hi,
Have you seen this resource?

<http://openptrack.org/>

I have not looked too deeply into it but they mention that it can track multiple people.
More importantly, it is open source.
<sub>[View in Slack](https://publictrans.slack.com/archives/CS8BUH8LC/p1579293469000700)</sub>
