### ISSUE TITLE
Researching python libraries for Counting people on the bus

### ISSUE THREAD

**Issue by erami201** [LTTien/MobilityEmbeddded#2]
## Description
Researching sensors/libraries that is compatible with the Pi

## Definition of Done
- [ ] find the library to use

## Tasks
- [ ] Come up with a library candidate to choose from and answer the following:
- [ ] compatible with pi?
- [ ] find the sensor(s) you need to use?
- [ ] are they open source or not?
